USE QLPHONGKHAM
GO

IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'NHA_SI' AND type = 'R')
BEGIN
    DROP ROLE NHA_SI;
    PRINT 'Role dropped.';
END
ELSE
BEGIN
	EXEC sys.sp_addrole @rolename = 'NHA_SI';
END;

GO

--DROP VIEW V_TKNHASI

CREATE OR ALTER VIEW V_TKNHASI
AS
	SELECT * FROM dbo.NhaSi 
	WHERE dbo.NhaSi.MaNS = CURRENT_USER
GO

CREATE OR ALTER VIEW V_TT_BENHNHAN
AS
	SELECT * FROM dbo.TaiKhoan
	WHERE dbo.TaiKhoan.LoaiTK = 'KH'
GO

CREATE OR ALTER VIEW V_THEM_HO_SO
AS
	SELECT * FROM dbo.HoSoKham
GO

CREATE OR ALTER VIEW V_TT_LOAI_DICHVU
AS
	SELECT * FROM dbo.DichVu
GO
--SELECT * FROM V_TT_LOAI_DICHVU
CREATE OR ALTER VIEW V_GHI_DICHVU_SD
AS
	SELECT * FROM dbo.HS_DV
GO

CREATE OR ALTER VIEW V_XEM_THUOC
AS
	SELECT * FROM dbo.Thuoc
GO

CREATE OR ALTER VIEW V_KEDONTHUOC
AS
	SELECT * FROM dbo.HS_T
GO
USE QLPHONGKHAM
SELECT * FROM dbo.V_KEDONTHUOC

CREATE OR ALTER VIEW V_XEM_THEM_SUA_LICHLAMVIEC
AS
	SELECT LLV.*
	FROM dbo.LichLamViec LLV, dbo.NhaSi NS
	WHERE LLV.MaNS = NS.MaNS
		AND NS.MaNS = CURRENT_USER
		AND LLV.LichBan = GETDATE()
GO

GRANT SELECT, UPDATE ON V_TKNHASI TO NHA_SI

GRANT SELECT ON V_TT_BENHNHAN TO NHA_SI

GRANT SELECT, INSERT ON V_THEM_BENH_AN TO NHA_SI

GRANT SELECT ON V_TT_LOAI_DICHVU TO NHA_SI

GRANT SELECT, INSERT ON V_GHI_DICHVU_SD TO NHA_SI

GRANT SELECT ON V_XEM_THUOC TO NHA_SI

GRANT SELECT, INSERT, UPDATE ON V_XEM_THEM_SUA_LICHLAMVIEC TO NHA_SI

GO
USE QLPHONGKHAM
SELECT * FROM dbo.NhanVien